/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/march-time-pages/CreateMemberPage': RouteRecordInfo<'/march-time-pages/CreateMemberPage', '/march-time-pages/CreateMemberPage', Record<never, never>, Record<never, never>>,
    '/march-time-pages/ImportCreatedMemberPage': RouteRecordInfo<'/march-time-pages/ImportCreatedMemberPage', '/march-time-pages/ImportCreatedMemberPage', Record<never, never>, Record<never, never>>,
    '/MarchTimesPage': RouteRecordInfo<'/MarchTimesPage', '/MarchTimesPage', Record<never, never>, Record<never, never>>,
    '/MinistryAppointments': RouteRecordInfo<'/MinistryAppointments', '/MinistryAppointments', Record<never, never>, Record<never, never>>,
    '/test-pages/ColorsPage': RouteRecordInfo<'/test-pages/ColorsPage', '/test-pages/ColorsPage', Record<never, never>, Record<never, never>>,
    '/test-pages/Test': RouteRecordInfo<'/test-pages/Test', '/test-pages/Test', Record<never, never>, Record<never, never>>,
    '/test-pages/TransitionTestPage': RouteRecordInfo<'/test-pages/TransitionTestPage', '/test-pages/TransitionTestPage', Record<never, never>, Record<never, never>>,
  }
}
